---
apiVersion: v1
kind: Service
metadata:
  name: svc1
  namespace: svc1-namespace
spec:
  selector:
    app.kubernetes.io/name: app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: d1
spec:
  template:
    spec:
      containers:
        - image: app1:1.0
          name: app
          env:
            - name: APP1_SERVICE
              value: "d1.app1"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: d2
spec:
  template:
    spec:
      containers:
        - image: app1:1.0
          name: app
          env:
            - name: APP1_SERVICE
              value: "d2.app1"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts1
spec:
  template:
    spec:
      containers:
        - image: app1:1.0
          name: app
          env:
            - name: APP1_SERVICE
              value: "app1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm1
data:
  APP1_SERVICE_PORT: "8080"
