apiVersion: kustomize-functions.zprd.io/v1
kind: ReplacementExtra

metadata:
  name: replacementServiceUrl
  annotations:
    config.kubernetes.io/function: |-
      exec:
        path: ./bin/replacementextra
#      container:
#        image: ghcr.io/zprd/kustomize-functions/replacement-extra:v1.0.0

replacements:
  - source:
      kind: Service
      name: svc1
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: Deployment|.*Set
        fieldPaths:
          - spec.template.spec.containers.*.env.[name=APP1_SERVICE].value
        options:
          index: 99
          delimiter: "."
  - source:
      kind: ConfigMap
      name: cm1
      fieldPath: data.APP1_SERVICE_PORT
    targets:
      - select:
          kind: Deployment|.*Set
        fieldPaths:
          - spec.template.spec.containers.*.env.[name=APP1_SERVICE].value
        options:
          index: 99
          delimiter: ":"

